### ISSUE TITLE
IBMi-bob setIBMiEnvCmd

### ISSUE THREAD

**Issue by cosentino-smeup** [IBM/vscode-ibmi-projectexplorer#584]
I have the following iproj.json:

```
{
  "version": "0.0.1",
  "description": "BOBMIN for IBM BOB test",
  "objlib": "&objlib",
  "curlib": "&srclib",
  "includePath": [
    "SRC"
  ],
  "preUsrlibl": [
    "&objlib",
    "&srclib"
  ],
  "postUsrlibl": [],
  "setIBMiEnvCmd": ["CRTDTAARA DTAARA(*CURLIB/PIPPO) TYPE(*CHAR) LEN(20) VALUE('&srclib    &objlib')"],
  "repository": "https://github.com/smeup/bob-min.git",
  "compileCommand": "/QOpenSys/pkgs/bin/makei c -f {filename}",
  "buildCommand": "/QOpenSys/pkgs/bin/makei build"
}
```

The command in the parameter "setIBMiEnvCmd" doesn't get executed "[when I connect to IBMi](https://ibm.github.io/ibmi-bob/#/prepare-the-project/iproj-json?id=configuration-options)" or when I start the build process.

`CRTDTAARA DTAARA(*CURLIB/PIPPO) TYPE(*CHAR) LEN(20) VALUE('&srclib    &objlib')`

**Comment by SanjulaGanepola** [comment]
> The command in the parameter "setIBMiEnvCmd" doesn't get executed "[when I connect to IBMi](https://ibm.github.io/ibmi-bob/#/prepare-the-project/iproj-json?id=configuration-options)" or when I start the build process.

@cosentino-smeup At the moment, `setIBMiEnvCmd` has limitations as mentioned [here](https://ibm.github.io/vscode-ibmi-projectexplorer/#/pages/ibm-i-projects/iproj-json?id=setibmienvcmd). In particular, "due to limitations in the way that Code for IBM i is architected they will not impact the LIBL shown in the Project Explorer UI". In fact, these commands are not being run at all right now by Project Explorer. We are still looking for a way to support this.

@edmundreinhardt As for the build process, does Bob itself run these commands or does PE need to run them before `makei build` is executed?

**Comment by edmundreinhardt** [comment]
@cosentino-smeup 
As you can see in this screen cap
<img width="658" alt="image" src="https://github.com/user-attachments/assets/de5e4acb-eec9-4878-81e8-db82b0e71591">

The command did get executed as "Data area FOO" was created
The problem is that it gets executed every time, so the second compile command complains that the data area already exists and fails as a result

What are you trying to achieve with this?

Is the DTAARA a prereq to some compiles? If so, it would be more effective to create CL pseudo source for it.
See the DTAARA in https://ibm.github.io/ibmi-bob/#/welcome/features
Even better see the example in https://github.com/IBM/bob-recursive-example in the QDTASRC directory

**Comment by edmundreinhardt** [comment]
make sure that any object that depends on the existing of this data area will have it in its depency

```
MYRPG.PGM: myrpg.pgm.rpgle PIPPO.DTAARA
PIPPO.DTAARA: pippo.dtaara
```
